# Generated by Django 4.0.6 on 2022-10-16 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id_alumno')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('documento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID Curso')),
                ('curso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id_profesor')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('documento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID Materia')),
                ('materia', models.CharField(max_length=50)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proa.cursos')),
                ('profesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proa.profesores')),
            ],
        ),
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID Calificacion')),
                ('nota', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('recuperatorio', models.BooleanField(default=False)),
                ('nota_final', models.IntegerField()),
                ('alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proa.alumno')),
                ('profesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proa.profesores')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proa.cursos'),
        ),
    ]
