# Generated by Django 4.2.1 on 2023-06-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proa', '0002_alter_cursos_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID Curso')),
                ('anio', models.IntegerField(verbose_name='Año')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('dni', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='DNI Profesor')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.RemoveField(
            model_name='calificaciones',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='calificaciones',
            name='profesor',
        ),
        migrations.RemoveField(
            model_name='materias',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='materias',
            name='profesor',
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Calificaciones',
        ),
        migrations.DeleteModel(
            name='Cursos',
        ),
        migrations.DeleteModel(
            name='Materias',
        ),
        migrations.DeleteModel(
            name='Profesores',
        ),
    ]
