# Generated by Django 4.2.1 on 2023-06-16 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proa', '0003_curso_profesor_remove_calificaciones_alumno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('dni', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('repitio', models.BooleanField(verbose_name='Repitio?')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proa.curso')),
            ],
        ),
    ]
