# Generated by Django 4.2.1 on 2023-06-16 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proa', '0004_alumno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID Materia')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Materia')),
                ('horas_catedra', models.IntegerField(verbose_name='Horas Catedra')),
                ('horario', models.CharField(max_length=100, verbose_name='Horario')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proa.curso')),
                ('profesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proa.profesor')),
            ],
        ),
    ]
