# Generated by Django 4.2.1 on 2023-06-16 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proa', '0005_materia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('final', models.BooleanField(verbose_name='final')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('nota', models.FloatField(verbose_name='Nota')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proa.alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proa.curso')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proa.materia')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proa.profesor')),
            ],
        ),
    ]
