# Generated by Django 4.2.2 on 2023-06-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proa', '0006_calificaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='repitio',
            field=models.BooleanField(default=None, null=True, verbose_name='Repitio?'),
        ),
    ]
