# Generated by Django 4.2.3 on 2023-08-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proa', '0009_alter_alumno_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('contraseña', models.CharField(max_length=100, verbose_name='Contraseña')),
                ('rol', models.CharField(max_length=1, verbose_name='Rol')),
            ],
        ),
    ]
