# Generated by Django 4.2.3 on 2023-08-08 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proa', '0010_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proa.usuario'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proa.usuario'),
        ),
    ]
