# Generated by Django 4.1.1 on 2023-08-08 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proa', '0012_alumno_inasistencias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña',
            new_name='contrasenia',
        ),
    ]
